import type { Metadata } from "next"
import "./globals.css"
import Sidebar from "@/components/Sidebar"

export const metadata: Metadata = {
	title: "QuickGPT",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body>
				<div className="flex">
					<div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
						<Sidebar />
					</div>

					{/* ClientProvider - Notifications */}

					<div className="bg-[#343541] flex-1">{children}</div>
				</div>
			</body>
		</html>
	)
}
